export const AUTH_SIGN_IN_BEGIN = "AUTH_SIGN_IN_BEGIN";
export const AUTH_SIGN_IN_SUCCESS = "AUTH_SIGN_IN_SUCCESS";
export const AUTH_SIGN_IN_FAILURE = "AUTH_SIGN_IN_FAILURE";
export const AUTH_SIGN_IN_DISMISS_ERROR = "AUTH_SIGN_IN_DISMISS_ERROR";

export const AUTH_SIGN_UP_BEGIN = "AUTH_SIGN_UP_BEGIN";
export const AUTH_SIGN_UP_SUCCESS = "AUTH_SIGN_UP_SUCCESS";
export const AUTH_SIGN_UP_FAILURE = "AUTH_SIGN_UP_FAILURE";
export const AUTH_SIGN_UP_DISMISS_ERROR = "AUTH_SIGN_UP_DISMISS_ERROR";

export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";




