export const ORDER_GET_BEGIN = "ORDER_GET_BEGIN";
export const ORDER_GET_SUCCESS = "ORDER_GET_SUCCESS";
export const ORDER_GET_FAILURE = "ORDER_GET_FAILURE";
export const ORDER_GET_DISMISS_ERROR = "ORDER_GET_DISMISS_ERROR";
export const ORDER_GET_ALL_BEGIN = "ORDER_GET_ALL_BEGIN";
export const ORDER_GET_ALL_SUCCESS = "ORDER_GET_ALL_SUCCESS";
export const ORDER_GET_ALL_FAILURE = "ORDER_GET_ALL_FAILURE";
export const ORDER_GET_ALL_DISMISS_ERROR = "ORDER_GET_ALL_DISMISS_ERROR";
export const ORDER_GET_BY_USER_BEGIN = "ORDER_GET_BY_USER_BEGIN";
export const ORDER_GET_BY_USER_SUCCESS = "ORDER_GET_BY_USER_SUCCESS";
export const ORDER_GET_BY_USER_FAILURE = "ORDER_GET_BY_USER_FAILURE";
export const ORDER_GET_BY_USER_DISMISS_ERROR =
  "ORDER_GET_BY_USER_DISMISS_ERROR";
export const ORDER_CREATE_BEGIN = "ORDER_CREATE_BEGIN";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAILURE = "ORDER_CREATE_FAILURE";
export const ORDER_CREATE_DISMISS_ERROR = "ORDER_CREATE_DISMISS_ERROR";
